[build]
# build-stage = 1
target = ["mipsel-sony-psx"]

[target."mipsel-sony-psx"]
rustflags = [
    "-Clink-arg=-Tpsexe.ld",
    "-Clink-arg=--oformat=binary",
    # "-Zlocation-detail=none",
]
runner = ["pcsx-redux", "-stdout", "-run", "-loadexe"]

[unstable]
build-std = [
    "core",
    "alloc",
    # "panic_abort",
]
build-std-features = [
    "compiler-builtins-mem",
    "optimize_for_size",
    # "panic_immediate_abort",
]
